version: "3.8"

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1500

services:
  dashboard:
    container_name: rma_fe
    build:
      context: ./
      dockerfile: ./Dockerfile
    working_dir: /app
    restart: unless-stopped
    volumes:
      - .:/app
    ports:
      - 3010:3010
    environment:
      TZ: ${TZ}
    #command: ["tail", "-f", "/dev/null"]
    command: ["sh", "-c", "./run.sh"]

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - dashboard
    links:
      - dashboard
